# Generated by Django 4.1.6 on 2023-02-08 12:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("coreapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="page",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
