# Generated by Django 4.1.7 on 2023-02-28 12:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coreapp", "0007_alter_user_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="likes",
            field=models.ManyToManyField(blank=True, related_name="liked", to=settings.AUTH_USER_MODEL),
        ),
    ]
