# Generated by Django 4.1.7 on 2023-03-01 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0008_post_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
