# Generated by Django 4.1.7 on 2023-03-01 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("coreapp", "0010_remove_page_is_blocked_page_is_permanently_blocked"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="page",
            name="is_permanently_blocked",
        ),
    ]
