# Generated by Django 4.1.7 on 2023-03-17 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0011_remove_page_is_permanently_blocked'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
