# Generated by Django 4.1.7 on 2023-03-17 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0012_user_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='image',
        ),
    ]
