# Generated by Django 4.1.7 on 2023-03-22 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0013_remove_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='image_s3_path',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='image',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='image_s3_path',
            field=models.TextField(blank=True, null=True),
        ),
    ]
