version: '3.7'

services:
  db:
    image: postgres:15.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5433:${POSTGRES_PORT}
    env_file:
      - ./.env
    healthcheck:
        test: [ "CMD", "pg_isready", "-q", "-d", "${POSTGRES_NAME}", "-U", "${POSTGRES_USER}" ]
        interval: 30s
        timeout: 60s
        retries: 5
        start_period: 80s
  web:
      build:
        dockerfile: Dockerfile
        context: .
      volumes:
         - .:/app
      ports:
        - 8000:8000
      env_file:
        - ./.env
      depends_on:
        db:
          condition: service_healthy

volumes:
  postgres_data: