version: "3.9"

services:
  test-db:
    image: postgres:15.1-alpine
    ports:
      - 5433:${POSTGRES_PORT}
    env_file:
      - ./.env.test
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "${POSTGRES_NAME}", "-U", "${POSTGRES_USER}" ]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
  test-web:
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - .:/app
    ports:
      - 8000:8000
    env_file:
      - ./.env.test
#    command: ["pytest"]
    command: "pytest --cov-config=/app/tests/.coveragerc --cov-report xml --cov-report term-missing --cov=./ /app/tests/"
#    volumes:
#      - "${WORKDIR}/src:/home/appuser/app/src"
#      - "${WORKDIR}/tests:/home/appuser/app/tests"
    depends_on:
      test-db:
        condition: service_healthy
